spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:weatherdb
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  config:
    import: optional:file:.env[.properties]

resilience4j:
  ratelimiter:
    instances:
      limit:
        limit-for-period: 10
        limit-refresh-period: 1m
        timeout-duration: 10s

weather_stack:
  api:
    url: http://api.weatherstack.com/current
    key: ${WEATHER_STACK_API_KEY:key-not-found}
  cache:
    weather:
      name: "weather"
      ttl: "900000"
